---
title: "GEODETIC DEFORMATION ANALYSIS REPORT"
author: "by DefAn-for-GNSS-networks"
date:  '`r format.Date (Sys.Date(),format = "%d %m %Y")`'
output: 
   pdf_document: default
   html_document: 
     df_print: paged
   word_document: default
always_allow_html: true
geometry: margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE, comment = NA)
```

## Parameters and Coordinates

```{r echo=FALSE, message=FALSE, warning=FALSE, comment=NA}
#for (p in 1:length(rms)){
#  cat(sprintf(rmslist[p]))
#  cat("\n")
#  cat("\n")
#}
```


Number of stations                     : `r length(both[[1]])`


```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
require(knitr)
for (p in 1:length(epochs)) {
  if("TRUE" %in% duplicated(matcdates)){
    print(knitr::kable(epochs[[p]], digits = 5, row.names = TRUE, align = "c", 
                     caption = sprintf("Coordinates of Epoch on %s",format.Date(dates[[p]],format = "%d-%m-%Y"))))
  cat('\n\n<!-- -->\n\n')
  }else {
    print(knitr::kable(epochs[[matcdates[p]]], digits = 5, row.names = TRUE, align = "c", 
                     caption = sprintf("Coordinates of Epoch on %s",format.Date(dates[[matcdates[p]]],format = "%d-%m-%Y"))))
  cat('\n\n<!-- -->\n\n')
  }
}
```


## Variance Ratio Test



```{r echo=FALSE, message=FALSE, warning=FALSE, comment=NA}
#for (p in 1:length(epochs)){
#  cat(sprintf(dflist[p]))
#  cat("\n")
#  cat("\n")
#}
for (p in 1:length(rms)){
  cat(sprintf(rmslist[p]))
  cat("\n")
  cat("\n")
}
```


```{r echo=FALSE, message=FALSE, warning=FALSE, comment=NA}
for (p in 1:length(pvlist)){
  cat(sprintf(pvlist[p]))
  cat("\n")
  cat("\n")
}
```
  **Pooled variance factor values are in** **$mm^2$**.

Significance Level of Variance Ratio Test           : 0.05

```{r echo=FALSE, message=FALSE, warning=FALSE, comment=NA}
require(knitr)
for (p in 1:length(tresult)){
  cat(sprintf(tresult[[p]]))
  cat("\n")
  cat("\n")
}
```



## Results of Geodetic Deformation Analysis 

Number of Iterations: `r it`


Significance Level of Single Point Test: 0.05

```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
require(knitr)
for (p in 1:length(both)) {
  if("TRUE" %in% duplicated(matcdates)){
    cat(sprintf("Critical Value on %s : %s",format.Date(dates[[p+1]],format = "%d-%m-%Y"),format(qf(0.95,3,dofort[[p]]),digits = 5 )))
    
    print(kable(restab[[p]], digits = 4, row.names = FALSE, align = "c", 
                     caption = sprintf("Single Point Test Results on %s",format.Date(dates[[p+1]],format = "%d-%m-%Y"))))
  cat('\n\n<!-- -->\n\n')
  }else {
    cat(sprintf("Critical Value on %s : %s",format.Date(dates[[matcdates[p+1]]],format = "%d-%m-%Y"),format(qf(0.95,3,dofort[[p]]),digits = 5 )))
    print(kable(restab[[p]], digits = 4, row.names = FALSE, align = "c", 
                     caption = sprintf("Single Point Test Results on %s",format.Date(dates[[matcdates[p+1]]],format = "%d-%m-%Y"))))
  cat('\n\n<!-- -->\n\n')
  }
  
  if("TRUE" %in% duplicated(matcdates)){
    print(knitr::kable(restab1[[p]], digits = 4, row.names = FALSE, align = "c", 
                     caption = sprintf("Displacements in Local Geodetic Coordinate System on %s",format.Date(dates[[p+1]],format = "%d-%m-%Y"))))
  cat('\n\n<!-- -->\n\n')
  }else {
    print(knitr::kable(restab1[[p]], digits = 4, row.names = FALSE, align = "c", 
                     caption = sprintf("Displacements in Local Geodetic Coordinate System on %s",format.Date(dates[[matcdates[p+1]]],format = "%d-%m-%Y"))))
  cat('\n\n<!-- -->\n\n')
  }
}
```

\newpage
## Plots of Point Displacements

Plots of displacements are given as follows.

```{r echo=FALSE, message=FALSE, fig.align = "center"}
for (p in 1:length(both)){
  if("TRUE" %in% duplicated(matcdates)){
    counts = matrix(as.numeric(restab[[p]][,2])/10,1,length(restab[[p]][,2]))
    counts = rbind(counts, as.numeric(restab[[p]][,3])/10)
    counts = rbind(counts, as.numeric(restab[[p]][,4])/10)
    colnames(counts) = c(both[[p]])
    rownames(counts) = c("DX","DY","DZ")
    barplot(counts, main=sprintf("Point Displacements in Direction of Coordinate Axes on %s",format.Date(dates[[p+1]],format = "%d-%m-%Y")), xlab="Name of Points", ylab="Displacement (cm)", col=c("blue","green","red"), legend = rownames(counts), beside=TRUE, space = c(0.4, 2.5), cex.main=0.75)
  
    counts = matrix(as.numeric(restab1[[p]][,2])/10,1,length(restab1[[p]][,2]))
    counts = rbind(counts, as.numeric(restab1[[p]][,3])/10)
    counts = rbind(counts, as.numeric(restab1[[p]][,4])/10)
    colnames(counts) = c(both[[p]])
    rownames(counts) = c("Dn","De","Du")
    barplot(counts, main=sprintf("Point Displacements in Direction of Topocentric Coordinate Axes on %s",format.Date(dates[[p+1]],format = "%d-%m-%Y")), xlab="Name of Points", ylab="Displacement (cm)", col=c("blue","green","red"), legend = rownames(counts), beside=TRUE, space = c(0.4, 2.5), cex.main=0.75)
  }else
    counts = matrix(as.numeric(restab[[p]][,2])/10,1,length(restab[[p]][,2]))
    counts = rbind(counts, as.numeric(restab[[p]][,3])/10)
    counts = rbind(counts, as.numeric(restab[[p]][,4])/10)
    colnames(counts) = c(both[[p]])
    rownames(counts) = c("DX","DY","DZ")
    barplot(counts, main=sprintf("Point Displacements in Direction of Coordinate Axes on %s",format.Date(dates[[matcdates[p+1]]],format = "%d-%m-%Y")), xlab="Name of Points", ylab="Displacement (cm)", col=c("blue","green","red"), legend = rownames(counts), beside=TRUE, space = c(0.4, 2.5), cex.main=0.75)
  
    counts = matrix(as.numeric(restab1[[p]][,2])/10,1,length(restab1[[p]][,2]))
    counts = rbind(counts, as.numeric(restab1[[p]][,3])/10)
    counts = rbind(counts, as.numeric(restab1[[p]][,4])/10)
    colnames(counts) = c(both[[p]])
    rownames(counts) = c("Dn","De","Du")
    barplot(counts, main=sprintf("Point Displacements in Direction of Topocentric Coordinate Axes on %s",format.Date(dates[[matcdates[p+1]]],format = "%d-%m-%Y")), xlab="Name of Points", ylab="Displacement (cm)", col=c("blue","green","red"), legend = rownames(counts), beside=TRUE, space = c(0.4, 2.5), cex.main=0.75)
}
```
